<?php
/**
 * Created by PhpStorm.
 * User: laiconglin
 * Date: 13/12/2017
 * Time: 21:45
 */

use Koala\Core\BaseController;

class HomeController extends BaseController
{
	protected function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function showAction() {
		$this->render('home/show', [
			'hello' => "页面主要内容",
			'headerTitle' => 'leliapp admin',
		]);
		return false;
	}

	public function whoamiAction() {
		$this->jsonOut(0, "ok", __METHOD__);
		return false;
	}

	public function queryNumAction() {
		$this->jsonOut(0, "ok", __METHOD__);
		return false;
	}

	public function queryAnyAction() {
		$this->jsonOut(0, "ok", __METHOD__);
		return false;
	}
}
